# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Galaxy Europe"
description: The European Galaxy Instance
email: contact@usegalaxy.eu
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://galaxyproject.eu" # the base hostname & protocol for your site, e.g. https://example.com
twitter_username: galaxyproject
github_username:  usegalaxy-eu
blurb:
    UseGalaxy.eu is maintained largely by the [Freiburg Galaxy
    Team](/freiburg/) but also collectively by groups and individuals from across
    Europe. All of the members sites in this repository contribute to the
    European Galaxy Project.

    All content on this site is available under
    [CC0-1.0](https://creativecommons.org/share-your-work/public-domain/cc0/),
    unless otherwise specified.

sass:
  sass_dir: assets/css

# Build settings
markdown: kramdown
kramdown:
  toc_levels: 1..2
#theme: minima
plugins:
  - jekyll-feed
  - jekyll/scholar
  - jekyll-twitter-plugin

scholar:
  style: bioinformatics
  group_by: year
  order: descending
  sort_by: year
  group_order: descending

citation:
    citation_style: apa
    citation_locale: en

team_sites:
    freiburg:
      name: Freiburg
      url: /freiburg/
      email: freiburg@usegalaxy.eu
      twitter_username: galaxyproject
      github_username: usegalaxy-eu
      private_news: true
      url: "https://usegalaxy.eu/freiburg/"
      galaxy_server: "https://usegalaxy.eu"
      blurb: |
        The [Freiburg Galaxy Team](/freiburg/people) is headed by Björn Grüning
        and is part of the [Bioinformatics Group
        Freiburg](http://www.bioinf.uni-freiburg.de), headed by Prof. Dr. Rolf
        Backofen.

        The team is part of [de.NBI](https://www.denbi.de) and
        [ELIXIR](https://www.elixir-europe.org) and largely funded by
        [DFG](http://dfg.de/) and [BMBF](https://www.bmbf.de). All content on
        this site is available under [CC0-1.0](https://creativecommons.org/share-your-work/public-domain/cc0/),
        unless otherwise specified.
    erasmusmc:
      name: Erasmus MC
      url: /erasmusmc/
      email: erasmusmc@usegalaxy.eu
      twitter_username: erasmusmc
      github_username: erasmusmc-bioinformatics
      private_news: true
      url: "https://www.erasmusmc.nl/bioinformatica/"
      galaxy_server: "https://bioinf-galaxian.erasmusmc.nl/galaxy/"
      blurb: |
          The EMC Galaxian server is maintained by the [Bioinformatics group](https://www.erasmusmc.nl/bioinformatica)
          in the [department of Pathology](https://www.erasmusmc.nl/pathologie) of the
          [Erasmus Medical Center](https://www.erasmusmc.nl), Rotterdam, The Netherlands.

          To inquire about this Galaxy server, increasing your disk quotum, or possibilities for collaborative
          projects, please contact one of our [team](/erasmusmc/people)
    belgium:
      name: VIB
      url: /vib/
      #email:
      #twitter_username: erasmusmc
      #github_username: erasmusmc-bioinformatics
      private_news: true
      url: "https://www.usegalaxy.be/"
      galaxy_server: "https://www.usegalaxy.be/"
      blurb: |
        Welcome to the Galaxy Instance of VIB - UGent Hosted at VSC (Flemish Supercomputer Centre)
    pasteur:
      name: Pasteur
      url: /pasteur/
      #email:
      #twitter_username:
      #github_username:
      private_news: true
      url: "https://galaxy.pasteur.fr/"
      galaxy_server: "https://galaxy.pasteur.fr/"
      blurb: ""

header_links:
    main:
        - name: News
          url: /news
        - name: Events
          url: /events
        - name: People
          url: /people
        - name: About
          url: /about
    freiburg:
        - name: News
          url: /freiburg/news
        - name: Events
          url: /freiburg/events
        - name: People
          url: /freiburg/people
        - name: Projects
          url: /freiburg/projects
        - name: Services
          url: /freiburg/services
        - name: Jobs
          url: /freiburg/jobs
        - name: Publications
          url: /freiburg/publications
    erasmusmc:
        - name: News
          url: /erasmusmc/news
        - name: Events
          url: /erasmusmc/events
        - name: People
          url: /erasmusmc/people
        - name: Publications
          url: /erasmusmc/publications
    belgium:
        - name: News
          url: /belgium/news
        - name: Events
          url: /belgium/events
        - name: People
          url: /belgium/people
        - name: Publications
          url: /belgium/publications
    pasteur:
        - name: News
          url: /pasteur/news
        - name: Events
          url: /pasteur/events
        - name: People
          url: /pasteur/people
        - name: Publications
          url: /pasteur/publications

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
#
# This will simultaneously render all collection items as "plain" pages
collections:
  posts:
    permalink: /posts/:year/:month/:day/:title/
  posts_plain:
    permalink: /posts/:year/:month/:day/:title/plain.html
    output: true
  events:
    permalink: /event/:path/
    output: true
  events_ical:
    permalink: /event/:path/event.ics
    output: true
  events_plain:
    permalink: /event/:path/plain.html
    output: true

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: news
  -
    scope:
      path: "_posts_plain"
    values:
      layout: news-galaxy
  -
    scope:
      path: "_events"
    values:
      layout: event
  -
    scope:
      path: "_events_ical"
    values:
      layout: event-ical
  -
    scope:
      path: "_events_plain"
    values:
      layout: event-galaxy
