name: usegalaxy-eu-website
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - ca-certificates
  - pyzotero
  - bibtexparser
  - readline
  - ruby=3.4
  - xz
  - zlib
  - gxx_linux-64
