name: usegalaxy-eu-website
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2019.6.16
  - gdbm=1.18
  - gmp=6.1.2
  - icu=64.2
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libiconv=1.15
  - libstdcxx-ng=9.1.0
  - libxml2=2.9.9
  - libxslt=1.1.33
  - ncurses=6.1
  - openssl=1.1.1c
  - rb-activesupport=4.2.11.1
  - rb-addressable=2.7.0
  - rb-bibtex-ruby=4.4.7
  - rb-citeproc=1.0.9
  - rb-citeproc-ruby=1.1.10
  - rb-colorator=1.1.0
  - rb-concurrent-ruby=1.1.5
  - rb-csl=1.5.0
  - rb-csl-styles=1.0.1.9
  - rb-em-websocket=0.5.1
  - rb-ethon=0.9.1
  - rb-eventmachine=1.2.7
  - rb-ffi=1.11.1
  - rb-forwardable-extended=2.6.0
  - rb-html-proofer=3.11.1
  - rb-http_parser.rb=0.6.0
  - rb-i18n=0.9.5
  - rb-jekyll=4.0.0
  - rb-jekyll-compose=0.11.0
  - rb-jekyll-feed=0.12.1
  - rb-jekyll-sass-converter=2.0.0
  - rb-jekyll-scholar=6.2.0
  - rb-jekyll-twitter-plugin=2.0.0
  - rb-jekyll-watch=2.2.1
  - rb-kramdown=2.1.0
  - rb-kramdown-parser-gfm=1.1.0
  - rb-latex-decode=0.3.1
  - rb-liquid=4.0.3
  - rb-listen=3.1.5
  - rb-mercenary=0.3.6
  - rb-mini_portile2=2.4.0
  - rb-minitest=5.11.3
  - rb-namae=1.0.1
  - rb-nokogiri=1.10.4
  - rb-parallel=1.17.0
  - rb-pathutil=0.16.2
  - rb-public_suffix=4.0.1
  - rb-rainbow=3.0.0
  - rb-rb-fsevent=0.10.3
  - rb-rb-inotify=0.10.0
  - rb-rouge=3.9.0
  - rb-ruby_dep=1.5.0
  - rb-safe_yaml=1.0.5
  - rb-sass=3.7.4
  - rb-sass-listen=4.0.0
  - rb-sassc=2.2.0
  - rb-terminal-table=1.8.0
  - rb-thread_safe=0.3.6
  - rb-typhoeus=1.3.1
  - rb-tzinfo=1.2.5
  - rb-tzinfo-data=1.2019.2
  - rb-unicode-display_width=1.6.0
  - rb-yell=2.2.0
  - readline=8.0
  - ruby=2.5.5
  - tk=8.6.9
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11

